from market_data.trade_day.bao_stock.producer import TradeDayProducer as BaoStockTradeDayProducer
from market_data.trade_day.bao_stock.processor import TradeDayProcessor as BaoStockTradeDayProcessor
from market_data.trade_day.bao_stock.storager import TradeDayStorager as BaoStockTradeDayStorager

BaoStockTradeDayProducer.set_component_name('BaoStockTradeDayProducer')
BaoStockTradeDayProcessor.set_component_name('BaoStockTradeDayProcessor')
BaoStockTradeDayStorager.set_component_name('BaoStockTradeDayStorager')
