from market_data.transaction_data.stock.tencent_api.processor import \
    TransactionDataProcessor as TencentApiTransactionDataProcessor
from market_data.transaction_data.stock.tencent_api.producer import \
    TransactionDataProducer as TencentApiTransactionDataProducer
from market_data.transaction_data.stock.tencent_api.storager import \
    TransactionDataStorager as TencentApiTransactionDataStorager

TencentApiTransactionDataProducer.set_component_name('TencentApiTransactionDataProducer')
TencentApiTransactionDataProcessor.set_component_name('TencentApiTransactionDataProcessor')
TencentApiTransactionDataStorager.set_component_name('TencentApiTransactionDataStorager')
